name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Anonymized Link Index
        uses: rcrimp/hugo-obsidian@v2.7.c
        with:
          index: true
          input: content
          output: data

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master # deploying branch
          cname: reubencrimp.com/notes
